[package]
name = "evm"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
build = "build.rs"

[dependencies]
etcommon-bigint = { version = "0.2", features = ["string", "rlp"], default-features = false }
etcommon-hexutil = { version = "0.2", default-features = false }
sha3 = "0.6"
sputnikvm = { version = "0.9", default-features = false }
evm-api = { path = "./api" }
ekiden-core = { git = "https://github.com/oasislabs/ekiden", tag = "0.1.0-alpha.3" }
ekiden-trusted = { git = "https://github.com/oasislabs/ekiden", tag = "0.1.0-alpha.3" }
protobuf = "1.4.3"

[build-dependencies]
ekiden-tools = { git = "https://github.com/oasislabs/ekiden", tag = "0.1.0-alpha.3" }
ekiden-edl = { git = "https://github.com/oasislabs/ekiden", tag = "0.1.0-alpha.3" }
