[package]
name = "runtime-evm"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
build = "build.rs"

[dependencies]
ekiden-core = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ekiden-trusted = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ethcore = { git = "https://github.com/ekiden/parity", branch = "sterling" }
ethereum-types = { git = "https://github.com/ekiden/primitives", branch = "ekiden" }
evm-api = { path = "./api" }
hex = "0.3"
log = "0.4"
protobuf = "~1.4"
sha3 = "0.6"

[build-dependencies]
ekiden-edl = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ekiden-tools = { git = "https://github.com/oasislabs/ekiden", branch = "master" }

[patch."https://github.com/ekiden/parity"]
common-types = { git = "https://github.com/ekiden/parity", branch = "sterling" }
#[patch.crates-io]
#ring = { git = "https://github.com/ekiden/ring", branch = "0.12.1-ekiden"}
