[package]
name = "evm"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
build = "build.rs"

[dependencies]
sha3 = "0.6"
evm-api = { path = "./api" }
ethcore = { path = "/sterling/parity/parity/ethcore" }
ethereum-types = { path = "/sterling/parity/primitives/ethereum-types" }
ekiden-core = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ekiden-trusted = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
protobuf = "~1.4"
log = "0.4"
hex = "0.3"

[build-dependencies]
ekiden-tools = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ekiden-edl = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
