[package]
name = "web3-gateway"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>", "Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
slog = "2.4.1"
parking_lot = "0.5"
rayon = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
fdlimit = "0.1"
signal-hook = "0.1.8"
prometheus = { version = "0.4.2", features = ["push"] }
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
lazy_static = "1.3.0"
wasmi = "0.4"
ethcore = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
ethcore-bytes = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
ethcore-transaction = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
ethereum-types = { version = "0.3", default-features = false, features = ["std", "serialize"] }
rlp = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
rlp_compress = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
parity-reactor = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
parity-rpc = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
keccak-hash = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
kvdb = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
mem = { git = "https://github.com/oasislabs/parity", branch = "kryha" }
common-types = { git = "https://github.com/oasislabs/parity", branch = "kryha" }

## Common functionality between runtime and gateway
runtime-ethereum-common = { path = "../common" }

## Ekiden client dependencies
clap = "2.29.1"
ekiden-client = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ekiden-runtime = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ekiden-keymanager-client = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
runtime-ethereum-api = { path = "../api" }
rand = "0.4"
grpcio = "0.4.4"
tokio = "0.1.17"
failure = "0.1.5"
io-context = "0.2.0"

[build-dependencies]
rustc_version = "0.2"

[dev-dependencies]
hex = "0.3"

[features]
default = ["pubsub"]
pubsub = []
production-genesis = []

[[bin]]
name = "gateway"
path ="bin/main.rs"
