################################
# Buildkite benchmarks pipeline
################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v3.0.1-oasis1:
    image: "oasislabs/testing:0.3.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      - /var/lib/buildkite-agent/.ssh:/root/.ssh
      - /var/lib/buildkite-agent/.coveralls:/root/.coveralls
      - /var/lib/buildkite-agent/.buildkite:/root/.buildkite
      # Shared Rust target artifacts cache.
      - /tmp/cargo_target:/cargo_target
      # Shared Rust package checkouts directory.
      - /tmp/cargo_pkg/git:/root/.cargo/git
      - /tmp/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /tmp/xargo_cache:/root/.xargo
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/cargo_target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
    propagate-environment: true
    unconfined: true

steps:
  - label: Build runtime benchmark
    command:
      - .buildkite/scripts/build_tag_push_benchmark_image.sh
    agents:
      buildkite_agent_size: large

  - wait

  - label: "Trigger benchmark run"
    trigger: private-ops-run-benchmarks
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master
