###########################
# Daily buildkite pipeline
###########################
# This pipeline is scheduled to be run daily at midnight UTC.
# Steps in the pipeline should only contain async triggers
# to other pipelines that will be triggered daily.

steps:
  - label: Trigger benchmark build
    branches: master
    trigger: oasis-runtime-benchmarks-build-image-context
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: "${BUILDKITE_BRANCH}"
