##################################
# Docker image deployment pipeline
##################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v2.1.0-oasis4:
    image: "oasislabs/development:0.2.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      - /var/lib/buildkite-agent/.ssh:/root/.ssh
      # Shared Rust incremental compile caches.
      - /tmp/cargo_ic/release:/workdir/target/release/incremental
      - /tmp/cargo_ic/release_sgx:/workdir/target/x86_64-unknown-linux-sgx/release/incremental
      # Shared Rust package checkouts directory.
      - /tmp/cargo_pkg/git:/root/.cargo/git
      - /tmp/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /tmp/xargo_cache:/root/.xargo
      # Shared Go package checkouts directory.
      - /tmp/go_pkg:/root/go/pkg
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/workdir/target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
    propagate-environment: true

steps:
  - label: Extract simulation platform resources
    branches: master beta
    command:
      - .buildkite/scripts/extract_platform_resources.sh sim-platform
    artifact_paths:
      - sim-platform/*

  - label: Extract hardware platform resources
    branches: master
    command:
      - .buildkite/scripts/extract_platform_resources.sh hw-platform
    artifact_paths:
      - hw-platform/*
    env:
      DEPLOYMENT_VARIANT: hw

  - wait

  - label: Get docker tag and save it as metadata for use later
    command: .buildkite/scripts/set_docker_tag_meta_data.sh

  - label: Build simulation artifacts (master branches only)
    branches: master beta
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - eval $(ssh-agent -s)
      - ssh-add
      - .buildkite/scripts/build_deployment_context.sh sim-platform sim-context.tar.gz
    artifact_paths:
      - sim-context.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Build hardware artifacts (master branches only)
    branches: master
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - eval $(ssh-agent -s)
      - ssh-add
      - .buildkite/scripts/build_deployment_context.sh hw-platform hw-context.tar.gz
    artifact_paths:
      - hw-context.tar.gz
    env:
      SGX_MODE: hw
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - wait

  - label: Update staging docker image tags (master branches only)
    branches: master
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh sim-context.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh staging

  - label: Update staging beta docker image tags (beta branch only)
    branches: beta
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh sim-context.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh staging-beta

  - label: Update hardware staging docker image tags (master branches only)
    branches: master
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh hw-context.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh staging-hw
    env:
      DEPLOYMENT_VARIANT: hw

  - wait

  - label: "Trigger staging deployment (master branches only)"
    trigger: private-ops-deploy-ekiden-staging
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master

  - label: "Trigger staging beta deployment (beta branch only)"
    trigger: private-ops-deploy-ekiden-staging-beta
    branches: beta
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master

  - label: "Trigger hardware staging deployment (master branches only)"
    trigger: private-ops-deploy-ekiden-hardware-staging
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master
