# `copper` is chosen as a random word for use as a key for labels that
# aren't naturally structured as key-value pairs.

kind: Service
apiVersion: v1
metadata:
  name: runtime-node-dummy
spec:
  ports:
    - name: dummy-grpc
      port: 42261
  selector:
    copper: runtime-node-dummy
  # type: ClusterIP
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: runtime-node-dummy
  labels:
    app: ekiden
spec:
  selector:
    matchLabels:
      copper: runtime-node-dummy
  # replicas: 1
  template:
    metadata:
      labels:
        copper: runtime-node-dummy
        app: ekiden
    spec:
      containers:
        - name: ekiden-node-dummy
          image: docker.io/oasislabs/ekiden-runtime-ethereum:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret
          command:
            - ekiden-node-dummy
          args:
            - --random-beacon-backend
            - dummy
            - --time-source-notifier
            - mock
            - --mock-epoch-interval
            - "600"
            - --storage-backend
            - persistent
            - --prometheus-metrics-addr
            - "0.0.0.0:3000"
            - --prometheus-mode
            - pull
          volumeMounts:
            - mountPath: /persistent-storage
              name: kx-evm-dummy-storage-persistent
      volumes:
        - name: kx-evm-dummy-storage-persistent
          awsElasticBlockStore:
            volumeID: vol-0559e233828c46577
---
kind: Service
apiVersion: v1
metadata:
  name: runtime
spec:
  ports:
    - name: contract-grpc
      port: 9001
  selector:
    copper: runtime
  # Change this to make the network public.
  # type: ClusterIP
---
# Should we go stateful and save the identity?
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: runtime
  labels:
    app: ekiden
spec:
  selector:
    matchLabels:
      copper: runtime
  replicas: 24
  template:
    metadata:
      labels:
        copper: runtime
        app: ekiden
    spec:
      containers:
        - name: ekiden-compute
          image: docker.io/oasislabs/ekiden-runtime-ethereum:latest
          env:
            - name: LD_LIBRARY_PATH
              value: /opt/intel/sgxsdk/lib64
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret
          command:
            - ekiden-compute
          args:
            - --no-persist-identity
            - --max-batch-timeout
            - "10"
            - --time-source-notifier
            - "system"
            - --entity-ethereum-address
            - "0000000000000000000000000000000000000000"
            - --prometheus-metrics-addr
            - "0.0.0.0:3000"
            - --prometheus-mode
            - pull
            - --consensus-client-host
            - $(EVM_NODE_DUMMY_SERVICE_HOST)
            - --consensus-client-port
            - $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
            - --contract-registry-client-host
            - $(EVM_NODE_DUMMY_SERVICE_HOST)
            - --contract-registry-client-port
            - $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
            - --entity-registry-client-host
            - $(EVM_NODE_DUMMY_SERVICE_HOST)
            - --entity-registry-client-port
            - $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
            - --scheduler-client-host
            - $(EVM_NODE_DUMMY_SERVICE_HOST)
            - --scheduler-client-port
            - $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
            - --batch-storage
            - multilayer
            - --storage-multilayer-sled-storage-base
            - /tmp/ekiden-storage-persistent
            - --storage-multilayer-bottom-backend
            - remote
            - --storage-multilayer-client-host
            - $(EVM_NODE_DUMMY_SERVICE_HOST)
            - --storage-multilayer-client-port
            - $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
            - ekiden/lib/runtime-ethereum.so

---
kind: Service
apiVersion: v1
metadata:
  name: web3-gateway
spec:
  ports:
    - name: web3
      port: 8545
      nodePort: 8545
  selector:
    copper: web3-gateway
  type: NodePort
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: web3-gateway
spec:
  selector:
    matchLabels:
      copper: web3-gateway
  template:
    metadata:
      labels:
        copper: web3-gateway
        app: ekiden
    spec:
      containers:
        - name: web3-gateway
          image: docker.io/oasislabs/ekiden-runtime-ethereum:latest
          command:
            - sh
          args:
            - -c
            - >-
              exec gateway
              --prometheus-metrics-addr 0.0.0.0:3000
              --prometheus-mode pull
              --entity-registry-client-host $(EVM_NODE_DUMMY_SERVICE_HOST)
              --entity-registry-client-port $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
              --scheduler-client-host $(EVM_NODE_DUMMY_SERVICE_HOST)
              --scheduler-client-port $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
              --consensus-client-host $(EVM_NODE_DUMMY_SERVICE_HOST)
              --consensus-client-port $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
              --storage-client-host $(EVM_NODE_DUMMY_SERVICE_HOST)
              --storage-client-port $(EVM_NODE_DUMMY_SERVICE_PORT_DUMMY_GRPC)
              --mr-enclave $$(cat ekiden/res/runtime-ethereum.mrenclave)
              --threads 100
