[package]
name = "runtime-ethereum-common"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]

[dependencies]
# Ekiden.
ekiden-runtime = { git = "https://github.com/oasislabs/ekiden", branch = "master" }
ekiden-keymanager-client = { git = "https://github.com/oasislabs/ekiden", branch = "master" }

# Parity.
ethcore = { git = "https://github.com/oasislabs/parity", branch = "armani/cross" }
ethereum-types = { git = "https://github.com/oasislabs/primitives", branch = "ekiden" }
hashdb = { git = "https://github.com/oasislabs/parity", branch = "armani/cross" }
keccak-hash = { git = "https://github.com/oasislabs/parity", branch = "armani/cross" }
vm = { git = "https://github.com/oasislabs/parity", branch = "armani/cross" }

# Others.
elastic-array = "0.10"
failure = "0.1.5"
io-context = "0.2.0"
