[package]
name = "oasis-runtime-keymanager"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[package.metadata.fortanix-sgx]
heap-size = 134217728
stack-size = 2097152
threads = 2

[dependencies]
# The referenced commit has rust code compatible with artifacts in oasis-core
# release: 20.5, with some rust changes needed that were not yet present in
# that release.
# Once a new oasis-core release is made, update the references to point to the
# new release.
oasis-core-runtime = { git = "https://github.com/oasislabs/oasis-core", rev = "0757868e351a63ad44d52b0d2df44c16b4e5c823" }
oasis-core-keymanager-lib = { git = "https://github.com/oasislabs/oasis-core", rev = "0757868e351a63ad44d52b0d2df44c16b4e5c823" }
oasis-core-keymanager-api-common = { git = "https://github.com/oasislabs/oasis-core", rev = "0757868e351a63ad44d52b0d2df44c16b4e5c823" }

[build-dependencies]
oasis-core-tools = { git = "https://github.com/oasislabs/oasis-core", tag = "v20.5" }
