[package]
name = "oasis-runtime-keymanager"
version = "0.3.0-alpha"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[package.metadata.fortanix-sgx]
heap-size = 134217728
stack-size = 2097152
threads = 2

[dependencies]
# TODO: change commit hash once oasis-core PR is merged.
# This will have to target a specific commit until new oasis-core release is
# made.
oasis-core-runtime = { git = "https://github.com/oasislabs/oasis-core", rev = "f55cdff15da73f49beb68733147adfa29bb09866" }
oasis-core-keymanager-lib = { git = "https://github.com/oasislabs/oasis-core", rev = "f55cdff15da73f49beb68733147adfa29bb09866" }
oasis-core-keymanager-api-common = { git = "https://github.com/oasislabs/oasis-core", rev = "f55cdff15da73f49beb68733147adfa29bb09866" }

[build-dependencies]
oasis-core-tools = { git = "https://github.com/oasislabs/oasis-core", tag = "v20.5" }
